language: java
jdk:
- openjdk7
- oraclejdk7
script:
- if [ "$TRAVIS_JDK_VERSION" = "openjdk7" ] && [ "$TRAVIS_BRANCH" = "master" ] &&
  [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn deploy --settings maven-settings.xml;
  else mvn install; fi
matrix:
  allow_failures:
    jdk: oraclejdk7
env:
  global:
  - secure: oBnFWualFwngdEiqEW1UIgaQrr5yCMRak1aB1y8K/fq8B2RWscC2tZE6v1k4fiaKhZgki+C14ZyTGPFzt2WHyeEs4tFNdaHzceaCEMVILe8cZXk8BU3ufcxv/SPDrjjs3v/0j23dHpJdqT7vH9d58wcLuRxvTqSAzxcSBPvWITDOTHHC6bsfp8bTOupvhNADSaXoD0JrVXxG1A4ExC9fIZe6WTaTCP8w0ecBTqIAKOzOyj1USH1vz84p1lIOc1jtzYqco9I7/9KnHIU269p6ibpj+ExDblzSw2ISdIyvOhJIm7lvE9iNwShiI94kZwL9hC0uowj6/YZAz/ajqsY131VsSc/QG/p7Dh3E9wN+C2cGtwFkYEkXXoboML8ocl+om+xMaM5P1VJywVxrb8+ESYBerHYnfUlO4W8Rj/l82rLYDyj97ehQggYVU2YazrA+hG+6pV37fHqnwbFU6B09IipFtb9Wd2407C1w+M0NYuJvX1oIAJtmvJNRPxz1392IhRtqfGnplxxylBQ5k39yjsALnul/zcY3XkoKQeyqzHBNDcLx/WMyZFhgUXYKM+by2YUnJre747MulMgPICpVixgywCb29n3Pv9RC+/Euo3ExFymu9+1NmQOyGnWqTKM97uhs3zbuvdBALULcv4is3kyCTHRwPAw9kz3BnztKWhY=
  - secure: TWqIfX/O285Z7sa4Ks/VV9Kayzi4f/SqrkvPKZuxGzeU6iHbhEdcQgC69myonap731O3enfWAApFlRjFEwi5QRzqxadI7sbh1JhaUhgh/t5S8Yva+3RZa3v6Idg+J/mt84RkMtarxtLWvZfFYjVEqzC5TkoEpp33AQ7GRG0bvgihqHrlRKo/KTd/UWfULISYb/7KQAtNsjmGFhzE026SywJQiUGBPUHd4yw0DfgPFXbrwvIAv3W8Dpn2vhIe/aRizXJg10tFU8oJ7NYO5ZKg0AtH/ZQoRB3jLQEy86aEX1SU+scpLOv/ZZcOuHyh+HrhtBTfVFZmSqzdII50mQh5z4war/Ww9VcB/fGVZ/RBogjbY0oprhVKi+ZP9DFvkUGpR//JXj7FW3NTSQhx8IMGMkpb1Pi16sQZFPuRWNPQ06DPiS/vOf5lDm8n287Z+IopwVIlxpn1M8ClklVZpAvB9rl98qF6jpcaqPFP44MJH8K2C4dPEx0Bs74C34TiMFgdye05IHIgh5rUeJVkCthpNY6jV0BCrDgdVb8+5GYzU/vJEnAhJfOn6VppcFLgI4ziJ4rhYeijReUc6P9GPggNOCAHMfRJGbaPte2zjGVtJG8ln7xlZH8XvoqlHtJ5TWWt84umsvU9PnCVmcBuDs35nZ/79ziui5xWE/PlS8yl480=
